/************************************************
 * Includes 
 * *********************************************/
#include <Arduino.h>
#include "hardware.h"


/************************************************
 * Statics 
 * *********************************************/

button_hw_t G_BUTTON_HW_MAP[NUM_BUTTONS] =
    {
        {
            BUTTON_01_PIN,
            LOW,
            5,
            0,
            0,
            HIGH,
        },
        {
            BUTTON_02_PIN,
            LOW,
            5,
            0,
            0,
            HIGH,
        },
        {
            BUTTON_03_PIN,
            LOW,
            5,
            0,
            0,
            HIGH,
        },
        {
            BUTTON_04_PIN,
            LOW,
            5,
            0,
            0,
            HIGH,
        },
        {
            BUTTON_05_PIN,
            LOW,
            5,
            0,
            0,
            HIGH,
        },
        {
            BUTTON_06_PIN,
            LOW,
            5,
            0,
            0,
            HIGH,
        },
        {
            BUTTON_07_PIN,
            LOW,
            5,
            0,
            0,
            HIGH,
        },
        {
            BUTTON_08_PIN,
            LOW,
            5,
            0,
            0,
            HIGH,
        },
        {
            BUTTON_09_PIN,
            LOW,
            5,
            0,
            0,
            HIGH,
        },
        {
            BUTTON_10_PIN,
            LOW,
            5,
            0,
            0,
            HIGH,
        },
        {
            BUTTON_11_PIN,
            LOW,
            5,
            0,
            0,
            HIGH,
        },
        {
            BUTTON_12_PIN,
            LOW,
            5,
            0,
            0,
            HIGH,
        },
        {
            BUTTON_13_PIN,
            LOW,
            5,
            0,
            0,
            HIGH,
        },
        {
            BUTTON_14_PIN,
            LOW,
            5,
            0,
            0,
            HIGH,
        },
        {
            BUTTON_15_PIN,
            LOW,
            5,
            0,
            0,
            HIGH,
        },
        {
            ENCODER_1_BUT_PIN,
            LOW,
            50,
            0,
            0,
            HIGH,
        },

};
